# Generated by Django 2.2.7 on 2019-11-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191124_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Tecnológico de Monterrey', [('carreta', 'carreta'), ('centro estudiantil', 'centro estudiantil')]), ('Pabellón M', [('Sala 1', 'Sala 1'), ('Sala 2', 'Sala 2'), ('Sala 3', 'Sala 3')])], default='carreta', max_length=20),
        ),
    ]
