# Generated by Django 2.2.7 on 2019-11-25 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20191124_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='room_name',
        ),
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Venue'),
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(default='not specified', max_length=300),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='venue',
            name='web',
            field=models.URLField(blank=True, verbose_name='Web Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Venue Name'),
        ),
    ]
