# Generated by Django 2.2.7 on 2019-11-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191125_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belonging_room_name', models.CharField(max_length=100, verbose_name='Room Name')),
                ('belonging_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Venue')),
            ],
        ),
    ]
