# Generated by Django 2.2.7 on 2019-11-25 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_venue_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='room_name',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='event',
            name='room_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Room'),
        ),
        migrations.DeleteModel(
            name='Venue_Room',
        ),
    ]
